status = warn
name = SparkLogConfig

rootLogger.level = error
rootLogger.appenderRefs = console
rootLogger.appenderRef.console.ref = console

appender.console.type = Console
appender.console.name = console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} | %-5p | %c | %m%n

logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = error

logger.spark.name = org.apache.spark
logger.spark.level = error
