/*
===============================================================================
File Name  : 13_CREATE_SILVER_INDEXES.sql
Schema     : DWH_SILVER
Purpose    : Create supporting Silver Layer indexes
===============================================================================
*/

CREATE INDEX IDX_SILVER_RECORD_HASH
ON SILVER_RECORD (RECORD_HASH);

CREATE INDEX IDX_SILVER_RECORD_LOAD_ID
ON SILVER_RECORD (LOAD_ID);

CREATE INDEX IDX_SILVER_POLICY_PERIOD
ON SILVER_POLICY (PERIOD);

CREATE INDEX IDX_SILVER_CUSTOMER_PERIOD
ON SILVER_CUSTOMER (PERIOD);

CREATE INDEX IDX_SILVER_PRODUCT_PERIOD
ON SILVER_PRODUCT (PERIOD);

CREATE INDEX IDX_SILVER_CHANNEL_PERIOD
ON SILVER_CHANNEL (PERIOD);

CREATE INDEX IDX_SILVER_COVERAGE_PERIOD
ON SILVER_COVERAGE (PERIOD);

CREATE INDEX IDX_SILVER_FINANCIAL_PERIOD
ON SILVER_FINANCIAL (PERIOD);

COMMIT;
