CREATE TABLE SILVER_STAGE
(
    ID VARCHAR2(100),
    ID_POLICY VARCHAR2(100) NOT NULL,
    ID_INSURED VARCHAR2(100) NOT NULL,
    PERIOD NUMBER NOT NULL,
    DATE_EFFECT_INSURED DATE,
    DATE_LAPSE_INSURED DATE,
    DATE_EFFECT_POLICY DATE,
    DATE_LAPSE_POLICY DATE,
    YEAR_EFFECT_INSURED NUMBER,
    YEAR_LAPSE_INSURED NUMBER,
    YEAR_EFFECT_POLICY NUMBER,
    YEAR_LAPSE_POLICY NUMBER,
    EXPOSURE_TIME NUMBER,
    LAPSE NUMBER,
    SENIORITY_INSURED NUMBER,
    SENIORITY_POLICY NUMBER,
    TYPE_POLICY VARCHAR2(20),
    TYPE_POLICY_DG VARCHAR2(20),
    TYPE_PRODUCT VARCHAR2(20),
    REIMBURSEMENT VARCHAR2(10),
    NEW_BUSINESS NUMBER,
    DISTRIBUTION_CHANNEL VARCHAR2(20),
    GENDER VARCHAR2(5),
    AGE NUMBER,
    PREMIUM NUMBER,
    COST_CLAIMS_YEAR NUMBER,
    N_MEDICAL_SERVICES NUMBER,
    RECORD_HASH VARCHAR2(64) NOT NULL,
    LOAD_ID NUMBER NOT NULL,
    LOAD_TIMESTAMP TIMESTAMP NOT NULL,
    SOURCE_FILE VARCHAR2(500) NOT NULL,
    ETL_CREATED_BY VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_SILVER_STAGE PRIMARY KEY (ID_POLICY, ID_INSURED, PERIOD)
);

COMMENT ON TABLE SILVER_STAGE IS
'Technical Silver staging table used only to support Spark-to-Oracle MERGE processing.';

CREATE INDEX IDX_SILVER_STAGE_HASH ON SILVER_STAGE (RECORD_HASH);

COMMIT;
