/*
===============================================================================
File Name  : 06_CREATE_SILVER_DQ_CHECKS.sql
Purpose    : Reusable Silver reconciliation and DQ checks
===============================================================================
*/

-- Observation-level Silver tables must reconcile to Bronze grain.
SELECT
    (SELECT COUNT(*) FROM DWH_BRONZE.BRONZE_POLICY_DATA) AS BRONZE_ROWS,
    (SELECT COUNT(*) FROM DWH_SILVER.SILVER_RECORD) AS SILVER_RECORD_ROWS,
    (SELECT COUNT(*) FROM DWH_SILVER.SILVER_POLICY) AS SILVER_POLICY_ROWS,
    (SELECT COUNT(*) FROM DWH_SILVER.SILVER_CUSTOMER) AS SILVER_CUSTOMER_ROWS,
    (SELECT COUNT(*) FROM DWH_SILVER.SILVER_PRODUCT) AS SILVER_PRODUCT_ROWS,
    (SELECT COUNT(*) FROM DWH_SILVER.SILVER_CHANNEL) AS SILVER_CHANNEL_ROWS,
    (SELECT COUNT(*) FROM DWH_SILVER.SILVER_COVERAGE) AS SILVER_COVERAGE_ROWS,
    (SELECT COUNT(*) FROM DWH_SILVER.SILVER_FINANCIAL) AS SILVER_FINANCIAL_ROWS
FROM DUAL;

-- Silver Time must contain one row per distinct Bronze period.
SELECT
    COUNT(DISTINCT PERIOD) AS BRONZE_PERIODS,
    (SELECT COUNT(*) FROM DWH_SILVER.SILVER_TIME) AS SILVER_PERIOD_ROWS
FROM DWH_BRONZE.BRONZE_POLICY_DATA;

-- Business-key duplicate checks.
SELECT 'SILVER_RECORD' TABLE_NAME, COUNT(*) DUPLICATE_KEYS
FROM (
    SELECT ID_POLICY, ID_INSURED, PERIOD
    FROM DWH_SILVER.SILVER_RECORD
    GROUP BY ID_POLICY, ID_INSURED, PERIOD
    HAVING COUNT(*) > 1
)
UNION ALL
SELECT 'SILVER_POLICY', COUNT(*) FROM (
    SELECT ID_POLICY, ID_INSURED, PERIOD FROM DWH_SILVER.SILVER_POLICY
    GROUP BY ID_POLICY, ID_INSURED, PERIOD HAVING COUNT(*) > 1
)
UNION ALL
SELECT 'SILVER_CUSTOMER', COUNT(*) FROM (
    SELECT ID_POLICY, ID_INSURED, PERIOD FROM DWH_SILVER.SILVER_CUSTOMER
    GROUP BY ID_POLICY, ID_INSURED, PERIOD HAVING COUNT(*) > 1
);

-- Required key null checks.
SELECT 'SILVER_POLICY' TABLE_NAME, COUNT(*) NULL_KEYS
FROM DWH_SILVER.SILVER_POLICY
WHERE ID_POLICY IS NULL OR ID_INSURED IS NULL OR PERIOD IS NULL;

-- Bronze -> Silver grain reconciliation.
SELECT COUNT(*) BRONZE_WITHOUT_SILVER
FROM DWH_BRONZE.BRONZE_POLICY_DATA b
WHERE NOT EXISTS (
    SELECT 1 FROM DWH_SILVER.SILVER_RECORD s
    WHERE s.ID_POLICY=b.ID_POLICY
      AND s.ID_INSURED=b.ID_INSURED
      AND s.PERIOD=b.PERIOD
);

SELECT COUNT(*) SILVER_WITHOUT_BRONZE
FROM DWH_SILVER.SILVER_RECORD s
WHERE NOT EXISTS (
    SELECT 1 FROM DWH_BRONZE.BRONZE_POLICY_DATA b
    WHERE b.ID_POLICY=s.ID_POLICY
      AND b.ID_INSURED=s.ID_INSURED
      AND b.PERIOD=s.PERIOD
);

-- Lineage/hash reconciliation.
SELECT COUNT(*) RECORD_HASH_MISMATCHES
FROM DWH_SILVER.SILVER_RECORD s
JOIN DWH_BRONZE.BRONZE_POLICY_DATA b
  ON b.ID_POLICY=s.ID_POLICY
 AND b.ID_INSURED=s.ID_INSURED
 AND b.PERIOD=s.PERIOD
WHERE b.RECORD_HASH <> s.RECORD_HASH;

-- Silver null coverage for technical lineage.
SELECT
    COUNT(*) TOTAL_ROWS,
    COUNT(RECORD_HASH) RECORD_HASH_POPULATED,
    COUNT(LOAD_ID) LOAD_ID_POPULATED,
    COUNT(LOAD_TIMESTAMP) LOAD_TIMESTAMP_POPULATED,
    COUNT(SOURCE_FILE) SOURCE_FILE_POPULATED,
    COUNT(ETL_CREATED_BY) ETL_CREATED_BY_POPULATED
FROM DWH_SILVER.SILVER_RECORD;
