/*
===============================================================================
File Name  : 17_CREATE_GOLD_DIMENSIONS.sql
Schema     : DWH_GOLD
Purpose    : Create frozen Gold Star Schema dimensions
===============================================================================
*/

CREATE TABLE DIM_TIME
(
    TIME_KEY NUMBER(10) NOT NULL,
    PERIOD   NUMBER(4)  NOT NULL,
    CONSTRAINT PK_DIM_TIME PRIMARY KEY (TIME_KEY),
    CONSTRAINT UK_DIM_TIME_PERIOD UNIQUE (PERIOD)
);

CREATE TABLE DIM_CUSTOMER
(
    CUSTOMER_KEY          NUMBER(10) NOT NULL,
    ID_POLICY             VARCHAR2(100) NOT NULL,
    ID_INSURED            VARCHAR2(100) NOT NULL,
    DATE_EFFECT_INSURED   DATE,
    DATE_LAPSE_INSURED    DATE,
    YEAR_EFFECT_INSURED   NUMBER(4),
    YEAR_LAPSE_INSURED    NUMBER(4),
    GENDER                VARCHAR2(5),
    CREATED_TIMESTAMP     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_TIMESTAMP     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ETL_CREATED_BY        VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_DIM_CUSTOMER PRIMARY KEY (CUSTOMER_KEY),
    CONSTRAINT UK_DIM_CUSTOMER_BK UNIQUE (ID_POLICY, ID_INSURED)
);

CREATE TABLE DIM_POLICY
(
    POLICY_KEY            NUMBER(10) NOT NULL,
    ID_POLICY             VARCHAR2(100) NOT NULL,
    TYPE_POLICY           VARCHAR2(20),
    TYPE_POLICY_DG        VARCHAR2(20),
    DATE_EFFECT_POLICY    DATE,
    DATE_LAPSE_POLICY     DATE,
    YEAR_EFFECT_POLICY    NUMBER(4),
    YEAR_LAPSE_POLICY     NUMBER(4),
    CREATED_TIMESTAMP     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_TIMESTAMP     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ETL_CREATED_BY        VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_DIM_POLICY PRIMARY KEY (POLICY_KEY),
    CONSTRAINT UK_DIM_POLICY_BK UNIQUE (ID_POLICY)
);

CREATE TABLE DIM_PRODUCT
(
    PRODUCT_KEY           NUMBER(10) NOT NULL,
    TYPE_PRODUCT           VARCHAR2(20) NOT NULL,
    REIMBURSEMENT          VARCHAR2(10) NOT NULL,
    CREATED_TIMESTAMP      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_TIMESTAMP      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ETL_CREATED_BY         VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_DIM_PRODUCT PRIMARY KEY (PRODUCT_KEY),
    CONSTRAINT UK_DIM_PRODUCT_BK UNIQUE (TYPE_PRODUCT, REIMBURSEMENT)
);

CREATE TABLE DIM_CHANNEL
(
    CHANNEL_KEY            NUMBER(10) NOT NULL,
    DISTRIBUTION_CHANNEL   VARCHAR2(20) NOT NULL,
    CREATED_TIMESTAMP      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_TIMESTAMP      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ETL_CREATED_BY         VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_DIM_CHANNEL PRIMARY KEY (CHANNEL_KEY),
    CONSTRAINT UK_DIM_CHANNEL_BK UNIQUE (DISTRIBUTION_CHANNEL)
);

COMMENT ON TABLE DIM_TIME IS 'Gold year-level time dimension.';
COMMENT ON TABLE DIM_CUSTOMER IS 'Gold customer/insured relationship dimension at (ID_POLICY, ID_INSURED) identity.';
COMMENT ON TABLE DIM_POLICY IS 'Gold policy dimension at ID_POLICY identity.';
COMMENT ON TABLE DIM_PRODUCT IS 'Gold product dimension at (TYPE_PRODUCT, REIMBURSEMENT) identity.';
COMMENT ON TABLE DIM_CHANNEL IS 'Gold distribution channel dimension.';

COMMIT;
