/*
===============================================================================
File Name  : 18_CREATE_GOLD_FACT_POLICY.sql
Schema     : DWH_GOLD
Purpose    : Create frozen Gold FACT_POLICY
Grain      : (ID_POLICY, ID_INSURED, PERIOD)
===============================================================================
*/

CREATE TABLE FACT_POLICY
(
    POLICY_KEY            NUMBER(10) NOT NULL,
    CUSTOMER_KEY          NUMBER(10) NOT NULL,
    PRODUCT_KEY           NUMBER(10) NOT NULL,
    CHANNEL_KEY           NUMBER(10) NOT NULL,
    TIME_KEY              NUMBER(10) NOT NULL,

    ID_POLICY             VARCHAR2(100) NOT NULL,
    ID_INSURED            VARCHAR2(100) NOT NULL,
    PERIOD                NUMBER(4) NOT NULL,

    PREMIUM               NUMBER(18,4),
    COST_CLAIMS_YEAR      NUMBER(18,4),
    EXPOSURE_TIME         NUMBER(18,8),
    N_MEDICAL_SERVICES    NUMBER(10),

    AGE                   NUMBER(3),
    SENIORITY_POLICY      NUMBER(10),
    SENIORITY_INSURED     NUMBER(10),
    NEW_BUSINESS          NUMBER,
    LAPSE                  NUMBER,

    LOAD_ID               NUMBER NOT NULL,
    LOAD_TIMESTAMP        TIMESTAMP NOT NULL,
    SOURCE_FILE           VARCHAR2(500) NOT NULL,
    RECORD_HASH           VARCHAR2(64) NOT NULL,
    ETL_CREATED_BY        VARCHAR2(100) NOT NULL,

    CONSTRAINT PK_FACT_POLICY
        PRIMARY KEY (ID_POLICY, ID_INSURED, PERIOD),

    CONSTRAINT FK_FACT_POLICY_DIM_POLICY
        FOREIGN KEY (POLICY_KEY) REFERENCES DIM_POLICY(POLICY_KEY),

    CONSTRAINT FK_FACT_POLICY_DIM_CUSTOMER
        FOREIGN KEY (CUSTOMER_KEY) REFERENCES DIM_CUSTOMER(CUSTOMER_KEY),

    CONSTRAINT FK_FACT_POLICY_DIM_PRODUCT
        FOREIGN KEY (PRODUCT_KEY) REFERENCES DIM_PRODUCT(PRODUCT_KEY),

    CONSTRAINT FK_FACT_POLICY_DIM_CHANNEL
        FOREIGN KEY (CHANNEL_KEY) REFERENCES DIM_CHANNEL(CHANNEL_KEY),

    CONSTRAINT FK_FACT_POLICY_DIM_TIME
        FOREIGN KEY (TIME_KEY) REFERENCES DIM_TIME(TIME_KEY)
);

COMMENT ON TABLE FACT_POLICY IS
'Gold policy observation fact at (ID_POLICY, ID_INSURED, PERIOD) grain.';

COMMIT;
