/*
===============================================================================
File Name  : 21_GOLD_DQ_CHECKS.sql
Purpose    : Gold validation queries
===============================================================================
*/

-- Fact grain uniqueness
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT ID_POLICY || '|' || ID_INSURED || '|' || PERIOD) AS DISTINCT_BUSINESS_KEYS
FROM FACT_POLICY;

-- Dimension key uniqueness
SELECT COUNT(*) AS ROW_COUNT, COUNT(DISTINCT POLICY_KEY) AS DISTINCT_KEYS
FROM DIM_POLICY;

SELECT COUNT(*) AS ROW_COUNT, COUNT(DISTINCT CUSTOMER_KEY) AS DISTINCT_KEYS
FROM DIM_CUSTOMER;

SELECT COUNT(*) AS ROW_COUNT, COUNT(DISTINCT PRODUCT_KEY) AS DISTINCT_KEYS
FROM DIM_PRODUCT;

SELECT COUNT(*) AS ROW_COUNT, COUNT(DISTINCT CHANNEL_KEY) AS DISTINCT_KEYS
FROM DIM_CHANNEL;

SELECT COUNT(*) AS ROW_COUNT, COUNT(DISTINCT TIME_KEY) AS DISTINCT_KEYS
FROM DIM_TIME;

-- Fact foreign-key integrity
SELECT COUNT(*) AS INVALID_POLICY_KEYS
FROM FACT_POLICY f
LEFT JOIN DIM_POLICY d ON d.POLICY_KEY = f.POLICY_KEY
WHERE d.POLICY_KEY IS NULL;

SELECT COUNT(*) AS INVALID_CUSTOMER_KEYS
FROM FACT_POLICY f
LEFT JOIN DIM_CUSTOMER d ON d.CUSTOMER_KEY = f.CUSTOMER_KEY
WHERE d.CUSTOMER_KEY IS NULL;

SELECT COUNT(*) AS INVALID_PRODUCT_KEYS
FROM FACT_POLICY f
LEFT JOIN DIM_PRODUCT d ON d.PRODUCT_KEY = f.PRODUCT_KEY
WHERE d.PRODUCT_KEY IS NULL;

SELECT COUNT(*) AS INVALID_CHANNEL_KEYS
FROM FACT_POLICY f
LEFT JOIN DIM_CHANNEL d ON d.CHANNEL_KEY = f.CHANNEL_KEY
WHERE d.CHANNEL_KEY IS NULL;

SELECT COUNT(*) AS INVALID_TIME_KEYS
FROM FACT_POLICY f
LEFT JOIN DIM_TIME d ON d.TIME_KEY = f.TIME_KEY
WHERE d.TIME_KEY IS NULL;

-- Source-to-fact grain reconciliation
SELECT COUNT(*) AS SOURCE_NOT_IN_FACT
FROM DWH_SILVER.SILVER_RECORD s
LEFT JOIN FACT_POLICY f
  ON f.ID_POLICY = s.ID_POLICY
 AND f.ID_INSURED = s.ID_INSURED
 AND f.PERIOD = s.PERIOD
WHERE f.ID_POLICY IS NULL;

SELECT COUNT(*) AS FACT_NOT_IN_SOURCE
FROM FACT_POLICY f
LEFT JOIN DWH_SILVER.SILVER_RECORD s
  ON s.ID_POLICY = f.ID_POLICY
 AND s.ID_INSURED = f.ID_INSURED
 AND s.PERIOD = f.PERIOD
WHERE s.ID_POLICY IS NULL;

-- Dimension cardinality checks
SELECT COUNT(*) AS CUSTOMER_ROWS,
       COUNT(DISTINCT ID_POLICY || '|' || ID_INSURED) AS CUSTOMER_BUSINESS_KEYS
FROM DIM_CUSTOMER;

SELECT COUNT(*) AS PRODUCT_ROWS,
       COUNT(DISTINCT TYPE_PRODUCT || '|' || REIMBURSEMENT) AS PRODUCT_BUSINESS_KEYS
FROM DIM_PRODUCT;

SELECT COUNT(*) AS CHANNEL_ROWS,
       COUNT(DISTINCT DISTRIBUTION_CHANNEL) AS CHANNEL_BUSINESS_KEYS
FROM DIM_CHANNEL;

SELECT COUNT(*) AS TIME_ROWS,
       COUNT(DISTINCT PERIOD) AS TIME_BUSINESS_KEYS
FROM DIM_TIME;
