/*
===============================================================================
File Name  : 21_GOLD_DQ_CHECKS.sql
Purpose    : Consolidated Gold validation queries
===============================================================================
*/

SET SERVEROUTPUT ON;

PROMPT ============================================================
PROMPT 1. GOLD ROW COUNTS
PROMPT ============================================================

SELECT 'DIM_CHANNEL' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM DWH_GOLD.DIM_CHANNEL
UNION ALL SELECT 'DIM_CUSTOMER', COUNT(*) FROM DWH_GOLD.DIM_CUSTOMER
UNION ALL SELECT 'DIM_POLICY', COUNT(*) FROM DWH_GOLD.DIM_POLICY
UNION ALL SELECT 'DIM_PRODUCT', COUNT(*) FROM DWH_GOLD.DIM_PRODUCT
UNION ALL SELECT 'DIM_TIME', COUNT(*) FROM DWH_GOLD.DIM_TIME
UNION ALL SELECT 'FACT_POLICY', COUNT(*) FROM DWH_GOLD.FACT_POLICY
ORDER BY TABLE_NAME;

PROMPT ============================================================
PROMPT 2. FACT GRAIN / DUPLICATES
PROMPT ============================================================

SELECT COUNT(*) AS TOTAL_FACT_ROWS,
       COUNT(DISTINCT ID_POLICY || '|' || ID_INSURED || '|' || TO_CHAR(PERIOD)) AS DISTINCT_BUSINESS_KEYS,
       COUNT(*) - COUNT(DISTINCT ID_POLICY || '|' || ID_INSURED || '|' || TO_CHAR(PERIOD)) AS DUPLICATE_KEYS
FROM DWH_GOLD.FACT_POLICY;

PROMPT ============================================================
PROMPT 3. DIMENSION BUSINESS-KEY UNIQUENESS
PROMPT ============================================================

SELECT 'DIM_TIME' AS DIMENSION, COUNT(*) AS ROW_COUNT,
       COUNT(DISTINCT PERIOD) AS DISTINCT_BUSINESS_KEYS,
       COUNT(*) - COUNT(DISTINCT PERIOD) AS DUPLICATES
FROM DWH_GOLD.DIM_TIME
UNION ALL
SELECT 'DIM_CUSTOMER', COUNT(*),
       COUNT(DISTINCT ID_POLICY || '|' || ID_INSURED),
       COUNT(*) - COUNT(DISTINCT ID_POLICY || '|' || ID_INSURED)
FROM DWH_GOLD.DIM_CUSTOMER
UNION ALL
SELECT 'DIM_POLICY', COUNT(*),
       COUNT(DISTINCT ID_POLICY),
       COUNT(*) - COUNT(DISTINCT ID_POLICY)
FROM DWH_GOLD.DIM_POLICY
UNION ALL
SELECT 'DIM_PRODUCT', COUNT(*),
       COUNT(DISTINCT TYPE_PRODUCT || '|' || REIMBURSEMENT),
       COUNT(*) - COUNT(DISTINCT TYPE_PRODUCT || '|' || REIMBURSEMENT)
FROM DWH_GOLD.DIM_PRODUCT
UNION ALL
SELECT 'DIM_CHANNEL', COUNT(*),
       COUNT(DISTINCT DISTRIBUTION_CHANNEL),
       COUNT(*) - COUNT(DISTINCT DISTRIBUTION_CHANNEL)
FROM DWH_GOLD.DIM_CHANNEL;

PROMPT ============================================================
PROMPT 4. FACT FOREIGN-KEY INTEGRITY
PROMPT ============================================================

SELECT 'POLICY_KEY' AS FK_NAME, COUNT(*) AS INVALID_ROWS
FROM DWH_GOLD.FACT_POLICY f LEFT JOIN DWH_GOLD.DIM_POLICY d ON d.POLICY_KEY = f.POLICY_KEY
WHERE d.POLICY_KEY IS NULL
UNION ALL
SELECT 'CUSTOMER_KEY', COUNT(*)
FROM DWH_GOLD.FACT_POLICY f LEFT JOIN DWH_GOLD.DIM_CUSTOMER d ON d.CUSTOMER_KEY = f.CUSTOMER_KEY
WHERE d.CUSTOMER_KEY IS NULL
UNION ALL
SELECT 'PRODUCT_KEY', COUNT(*)
FROM DWH_GOLD.FACT_POLICY f LEFT JOIN DWH_GOLD.DIM_PRODUCT d ON d.PRODUCT_KEY = f.PRODUCT_KEY
WHERE d.PRODUCT_KEY IS NULL
UNION ALL
SELECT 'CHANNEL_KEY', COUNT(*)
FROM DWH_GOLD.FACT_POLICY f LEFT JOIN DWH_GOLD.DIM_CHANNEL d ON d.CHANNEL_KEY = f.CHANNEL_KEY
WHERE d.CHANNEL_KEY IS NULL
UNION ALL
SELECT 'TIME_KEY', COUNT(*)
FROM DWH_GOLD.FACT_POLICY f LEFT JOIN DWH_GOLD.DIM_TIME d ON d.TIME_KEY = f.TIME_KEY
WHERE d.TIME_KEY IS NULL;

PROMPT ============================================================
PROMPT 5. SILVER -> GOLD GRAIN RECONCILIATION
PROMPT ============================================================

SELECT 'SILVER_NOT_IN_GOLD' AS CHECK_NAME, COUNT(*) AS MISMATCH_ROWS
FROM DWH_SILVER.SILVER_RECORD s
LEFT JOIN DWH_GOLD.FACT_POLICY f
  ON f.ID_POLICY = s.ID_POLICY AND f.ID_INSURED = s.ID_INSURED AND f.PERIOD = s.PERIOD
WHERE f.ID_POLICY IS NULL
UNION ALL
SELECT 'GOLD_NOT_IN_SILVER', COUNT(*)
FROM DWH_GOLD.FACT_POLICY f
LEFT JOIN DWH_SILVER.SILVER_RECORD s
  ON s.ID_POLICY = f.ID_POLICY AND s.ID_INSURED = f.ID_INSURED AND s.PERIOD = f.PERIOD
WHERE s.ID_POLICY IS NULL;

PROMPT ============================================================
PROMPT 6. SILVER -> GOLD MEASURE RECONCILIATION
PROMPT ============================================================

SELECT 'PREMIUM' AS MEASURE,
       (SELECT SUM(PREMIUM) FROM DWH_SILVER.SILVER_FINANCIAL) AS SILVER_TOTAL,
       (SELECT SUM(PREMIUM) FROM DWH_GOLD.FACT_POLICY) AS GOLD_TOTAL,
       (SELECT SUM(PREMIUM) FROM DWH_GOLD.FACT_POLICY) -
       (SELECT SUM(PREMIUM) FROM DWH_SILVER.SILVER_FINANCIAL) AS DIFFERENCE
FROM DUAL
UNION ALL
SELECT 'COST_CLAIMS_YEAR',
       (SELECT SUM(COST_CLAIMS_YEAR) FROM DWH_SILVER.SILVER_FINANCIAL),
       (SELECT SUM(COST_CLAIMS_YEAR) FROM DWH_GOLD.FACT_POLICY),
       (SELECT SUM(COST_CLAIMS_YEAR) FROM DWH_GOLD.FACT_POLICY) -
       (SELECT SUM(COST_CLAIMS_YEAR) FROM DWH_SILVER.SILVER_FINANCIAL)
FROM DUAL
UNION ALL
SELECT 'EXPOSURE_TIME',
       (SELECT SUM(EXPOSURE_TIME) FROM DWH_SILVER.SILVER_COVERAGE),
       (SELECT SUM(EXPOSURE_TIME) FROM DWH_GOLD.FACT_POLICY),
       (SELECT SUM(EXPOSURE_TIME) FROM DWH_GOLD.FACT_POLICY) -
       (SELECT SUM(EXPOSURE_TIME) FROM DWH_SILVER.SILVER_COVERAGE)
FROM DUAL
UNION ALL
SELECT 'N_MEDICAL_SERVICES',
       (SELECT SUM(N_MEDICAL_SERVICES) FROM DWH_SILVER.SILVER_COVERAGE),
       (SELECT SUM(N_MEDICAL_SERVICES) FROM DWH_GOLD.FACT_POLICY),
       (SELECT SUM(N_MEDICAL_SERVICES) FROM DWH_GOLD.FACT_POLICY) -
       (SELECT SUM(N_MEDICAL_SERVICES) FROM DWH_SILVER.SILVER_COVERAGE)
FROM DUAL;

PROMPT ============================================================
PROMPT 7. TIME / PERIOD VALIDATION
PROMPT ============================================================

SELECT COUNT(*) AS TIME_ROWS, MIN(PERIOD) AS MIN_PERIOD,
       MAX(PERIOD) AS MAX_PERIOD, COUNT(DISTINCT PERIOD) AS DISTINCT_PERIODS
FROM DWH_GOLD.DIM_TIME;

SELECT PERIOD, COUNT(*) AS FACT_ROWS
FROM DWH_GOLD.FACT_POLICY
GROUP BY PERIOD
ORDER BY PERIOD;

PROMPT ============================================================
PROMPT 8. FACT NULL KEY CHECKS
PROMPT ============================================================

SELECT COUNT(*) AS TOTAL_ROWS,
       SUM(CASE WHEN POLICY_KEY IS NULL THEN 1 ELSE 0 END) AS NULL_POLICY_KEY,
       SUM(CASE WHEN CUSTOMER_KEY IS NULL THEN 1 ELSE 0 END) AS NULL_CUSTOMER_KEY,
       SUM(CASE WHEN PRODUCT_KEY IS NULL THEN 1 ELSE 0 END) AS NULL_PRODUCT_KEY,
       SUM(CASE WHEN CHANNEL_KEY IS NULL THEN 1 ELSE 0 END) AS NULL_CHANNEL_KEY,
       SUM(CASE WHEN TIME_KEY IS NULL THEN 1 ELSE 0 END) AS NULL_TIME_KEY,
       SUM(CASE WHEN ID_POLICY IS NULL THEN 1 ELSE 0 END) AS NULL_ID_POLICY,
       SUM(CASE WHEN ID_INSURED IS NULL THEN 1 ELSE 0 END) AS NULL_ID_INSURED,
       SUM(CASE WHEN PERIOD IS NULL THEN 1 ELSE 0 END) AS NULL_PERIOD
FROM DWH_GOLD.FACT_POLICY;

PROMPT ============================================================
PROMPT 9. GOLD DIMENSION CARDINALITY
PROMPT ============================================================

SELECT 'DIM_TIME' AS DIMENSION, COUNT(*) AS ROW_COUNT FROM DWH_GOLD.DIM_TIME
UNION ALL SELECT 'DIM_CUSTOMER', COUNT(*) FROM DWH_GOLD.DIM_CUSTOMER
UNION ALL SELECT 'DIM_POLICY', COUNT(*) FROM DWH_GOLD.DIM_POLICY
UNION ALL SELECT 'DIM_PRODUCT', COUNT(*) FROM DWH_GOLD.DIM_PRODUCT
UNION ALL SELECT 'DIM_CHANNEL', COUNT(*) FROM DWH_GOLD.DIM_CHANNEL;
