"""
==========================================================
Project : Insurance Risk Intelligence Platform
Module  : Source File Hash Utility
Author  : Saurabh Singh

Description
-----------
Provides a reusable SHA-256 checksum function for source
file lineage and ETL control-table tracking.

This hash is calculated from the exact raw file bytes.
It is intentionally separate from RECORD_HASH, which is a
row-level hash generated by hash_generator.py.

No ETL business transformation logic should exist here.

==========================================================
"""

import hashlib
from pathlib import Path

from utils.logger import get_logger


logger = get_logger(
    layer="bronze",
    module_name="file_hash"
)


def calculate_file_sha256(
    source_file: Path,
    chunk_size: int = 1024 * 1024
) -> str:
    """
    Calculates the SHA-256 checksum of the complete source
    file using its raw bytes.

    Parameters
    ----------
    source_file : Path
        Source CSV file.

    chunk_size : int
        Number of bytes read per iteration.

    Returns
    -------
    str
        Lowercase hexadecimal SHA-256 checksum.
    """

    if not source_file.is_file():
        raise FileNotFoundError(
            f"Source file not found: {source_file}"
        )

    sha256 = hashlib.sha256()

    with source_file.open("rb") as file_handle:
        while True:
            chunk = file_handle.read(chunk_size)

            if not chunk:
                break

            sha256.update(chunk)

    file_hash = sha256.hexdigest()

    logger.info(
        "Calculated source file SHA-256 | file=%s",
        source_file.name
    )

    return file_hash
